### ISSUE TITLE
Plugin not updated in Pub.dev

### ISSUE THREAD

**Issue by Poliin13** [Shahxad-Akram/flutter_tex#122]
1. The webview plugin not updated
2. lt's working only using local dependency

**Comment by shah-xad** [comment]
I didn't understand. What do you mean by "it's working only using local dependency"?

**Comment by Poliin13** [comment]
1. The plugin *doesn't work* if I use it directly from pub.dev:
      dependencies:
   flutter_tex: ^4.0.3+2
//Not working


2. If i download the repository from github, it works only with reference
like this:
dependencies:
flutter:
sdk: flutter
flutter_tex:
path: ../it needs a path to local repository.

Conclusion:
Revision needed in pub.deb

**Comment by shah-xad** [comment]
I don't know, why are you facing this issue, but I just tested it and it's working fine. just try `flutter clean` and then check again.

**Comment by Poliin13** [comment]
I made a new Test project just to check it. And ofcouse flutter clean. Reinstalled the plugin. The problem persists. Also the border shows: 
borderStyle: TeXViewBorderStyle.dolid, 
insted of "solid". 
I think you updated it. But it's not showing in flutter. 
Please help me.
![Screenshot (2)](https://user-images.githubusercontent.com/50265302/156191830-81223a56-8586-423f-b513-ecbe8ea6f7ad.png)

**Comment by shah-xad** [comment]
I have updated it, please try `4.0.3+3`.

**Comment by Poliin13** [comment]
Hi,
Sorry to bother you once again.
1. The border "Solid" was fixed 
2. But still not working
3. Did you test it on a New Flutter Project? Because downloading the repository works fine.
4. The weview_flutter_plugin is not updated.

![Screenshot 2022-03-03 142945](https://user-images.githubusercontent.com/50265302/156526406-4688917b-8af2-45c6-a5bc-bedaa33587a3.png)

![Screenshot 2022-03-03 142901](https://user-images.githubusercontent.com/50265302/156526396-982dfbcc-b28f-4e3d-9ad5-2f05a51aa77c.png)

**Comment by shah-xad** [comment]
I have updated the dependency, please check `4.0.3+4` and let me know.
