### ISSUE TITLE
Black Screen 

### ISSUE THREAD

**Issue by Ibrahim-Lokman** [Shahxad-Akram/flutter_tex#189]
When the user minimizes the screen and returns after some time (5 min), the rendered part with flutter_tex turns black.

Tested on many devices, but the issue is only found on the  pixel phone ( Pixel 6a, Android version 14, Google Tensor Chip).

Used: flutter_tex: ^4.0.6

<img width="278" alt="Screenshot 2024-06-26 at 3 48 34 PM" src="https://github.com/shah-xad/flutter_tex/assets/49040963/c8df8706-fe5e-4764-8551-1fbbe41f175b">
<img width="255" alt="Screenshot 2024-06-26 at 3 49 05 PM" src="https://github.com/shah-xad/flutter_tex/assets/49040963/8912b964-8429-4cb1-9771-ee2df11469ed">

**Comment by dakshvasudev** [comment]
I guess the reason might be that you are not using `scaffold`

**Comment by ibrahim-innospace** [comment]
> I guess the reason might be that you are not using `scaffold`

Solved by upgrading the flutter version. 

issue: 
https://github.com/flutter/flutter/issues/147849
